(string-append "Hello" " " "World")
(string-length "Hello")
(string-ref "Hello" 1)
(substring "Hello" 1 4)
(string=? "abc" "abc")
(string=? "abc" "def")
(string<? "abc" "def")
(string>? "def" "abc")
(number->string 42)
(number->string 3.14)
(string->number "123")
(string->number "3.14")
(string->number "not-a-number")
(string-upcase "hello")
(string-downcase "HELLO")
(string-append "Hi " (number->string 42) " times")
